--Parametrización inicial
--commit;
--rollback;

--select * from STATUS_TRACK
-- parametros STATUS_TRACK 

INSERT INTO STATUS_TRACK VALUES(1,'Iniciado');
INSERT INTO STATUS_TRACK VALUES(2,'En proceso');
INSERT INTO STATUS_TRACK VALUES(3,'En proceso/Devolución');
INSERT INTO STATUS_TRACK VALUES(4,'Entregado Ok');
INSERT INTO STATUS_TRACK VALUES(5,'Cancelado');

-- parametros STATUS_ORDER

INSERT INTO STATUS_ORDER VALUES(1,'Abierta');
INSERT INTO STATUS_ORDER VALUES(2,'En proceso');
INSERT INTO STATUS_ORDER VALUES(3,'Cerrada por el Cliente');
INSERT INTO STATUS_ORDER VALUES(4,'Cerrada por la empresa');
INSERT INTO STATUS_ORDER VALUES(5,'Entregado OK');

--Empresas de Envío
INSERT INTO EMPRESAS_ENVIO VALUES(0, 'No Aplica', 0, 'No Aplica');
INSERT INTO EMPRESAS_ENVIO VALUES(1, 'Guatexpreso', 23.35, 'Guatex');
INSERT INTO EMPRESAS_ENVIO VALUES(2, 'DHL', 40, 'DHL');
INSERT INTO EMPRESAS_ENVIO VALUES(3, 'ServiEntrega', 28, 'S.Entrega');

--Envios Internos
INSERT INTO ENVIOS_INTERNOS VALUES(0, 'No Aplica');
INSERT INTO ENVIOS_INTERNOS VALUES(33, 'creyes');
INSERT INTO ENVIOS_INTERNOS VALUES(77, 'ggiron');




/*
CREATE TABLE ENVIOS_INTERNOS(
 COD_EMPLEADO NUMBER(18), 
 TRACK_ALIAS VARCHAR2(150),
 PRIMARY KEY(COD_EMPLEADO)
);

*/

